server.port=8080

spring.application.name=api-gateway

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

logging.level.root=INFO

# ==========================================================
# PRODUCT SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/product,/api/product/**

# ==========================================================
# ORDER SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders,/api/orders/**

# ==========================================================
# INVENTORY SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[2].id=inventory-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/inventory,/api/inventory/**

# ==========================================================
# EUREKA DASHBOARD
# ==========================================================

spring.cloud.gateway.server.webflux.routes[3].id=discovery-server
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/eureka/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1


# ==========================================================
# USER SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[4].id=user-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/users,/api/users/**

# ==========================================================
# ORCHESTRATOR SERVICE
# ==========================================================
spring.cloud.gateway.server.webflux.routes[5].id=orchestrator-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://orchestrator-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/saga,/api/saga/**

# ==========================================================
# NOTIFICATION SERVICE
# ==========================================================
spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/notifications,/api/notifications/**


